# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lithia < Formula
  desc "Early development, experimental functional programming language with an implicit but strong and dynamic type system."
  homepage "https://github.com/vknabel/lithia"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.18/lithia_0.0.18_Darwin_arm64.tar.gz"
      sha256 "ec91e61651b3b3fc47e272a71d4f46622bbe5e30e33e01cc265b6dae6ac99cf1"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.18/lithia_0.0.18_Darwin_x86_64.tar.gz"
      sha256 "3774f4a1343f0e0fe2ef8f1362976ef1209eeff89df8c19f2d3b3e5f0efb4e21"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.18/lithia_0.0.18_Linux_arm64.tar.gz"
      sha256 "6f1ad5caea938d4a607cf60f828a5557f727b3e20bab4ddb6ee76f925c2da6df"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.18/lithia_0.0.18_Linux_x86_64.tar.gz"
      sha256 "dc82df3970a03af65f7946f77735c3017725140cab8d4c1391c804669c273174"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
  end
end
