# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lithia < Formula
  desc ""
  homepage ""
  version "0.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.16/lithia_0.0.16_Darwin_arm64.tar.gz"
      sha256 "44b70421e112a0a3dc8cae8b98021dd4959f6ec84611e8168b9b97a06bc8a648"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.16/lithia_0.0.16_Darwin_x86_64.tar.gz"
      sha256 "761b876011fbd490c986bc7a9b6ded06a92953aaa444aad0a9018d67b20cdf40"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.16/lithia_0.0.16_Linux_arm64.tar.gz"
      sha256 "344f37f31c916387c072c202c33c8d9063747b659d4c229448e27bbd726f43fd"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vknabel/lithia/releases/download/v0.0.16/lithia_0.0.16_Linux_x86_64.tar.gz"
      sha256 "405faf255cc16c31f16fcd95cce93b083c106b289d381c38b09e8ab38bbf7c33"

      def install
        bin.install "lithia"
        prefix.install "./stdlib"
      end
    end
  end
end
